# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bcrypt'
gem 'puma'
gem 'rackup'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 1.4'
group :development, :test do
  gem 'rack-test'
  gem 'rake'
  gem 'rspec'
end
gem 'database_cleaner'
gem 'rubocop', require: false
gem 'simplecov'
